##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################

# If the tool is built out of the kit, PIN_ROOT must be specified in the make invocation and point to the kit root.
override PIN_ROOT = /opt/pin

ifdef PIN_ROOT
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
CONFIG_ROOT := ../Config
endif
include $(CONFIG_ROOT)/makefile.config

TOOL_CXXFLAGS += -Wall -g -Wno-error
TOOL_LDFLAGS += -Wl,-rpath,/opt/pin/intel64/runtime

TEST_TOOL_ROOTS := numalize

include $(TOOLS_ROOT)/Config/makefile.default.rules
